<!--<title>Summit abstracts</title>-->
<!--Copyright 2022, seL4 summit authors (see abstracts)SPDX-License-Identifier: CC-BY-SA-4.0
-->

<h1>
  seL4 Summit 2022
</h1>
<h4>
Munich, Germany (hybrid), 10-13 Oct 2022
</h4>


<h3>
   Abstracts
</h3>
<div class="summit-abstract" id="a-seL4-research"><%@ include file="abstracts/seL4-research.pml" %><a href="https://www.youtube.com/watch?v=C3nOjXhyPfk" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_02_State_of_seL4-related_research_Gernot_Heiser.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program#p-seL4-research">See this talk in the program</a></div>
<div class="summit-abstract" id="a-seL4-verification-roadmap"><%@ include file="abstracts/seL4-verification-roadmap.pml" %><a href="https://www.youtube.com/watch?v=lvmjXO1jTec" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_03_seL4_verification-roadmap_Proofcraft.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-seL4-verification-roadmap">See this talk in the program</a></div>
<div class="summit-abstract" id="a-explaining-integrity-theorems"><%@ include file="abstracts/Explaining-integrity-theorems.pml" %><a href="https://www.youtube.com/watch?v=fyF9w_CsCEU" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_04_Explaining_the_seL4_integrity_theorems_Matt_Brecknell.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-explaining-integrity-theorems">See this talk in the program</a></div>
<div class="summit-abstract" id="a-seL4CP"><%@ include file="abstracts/seL4CP.pml" %><a href="https://www.youtube.com/watch?v=kRI4VQRSB_w" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_05_The_seL4_Core_Platform_(seL4CP)_Zoltan_Kocsis.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-seL4CP">See this talk in the program</a></div>
<div class="summit-abstract" id="a-sDDF"><%@ include file="abstracts/sDDF.pml" %><a href="https://www.youtube.com/watch?v=INBEKSkAiTA" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_06_The_seL4_Device_Driver_Framework_(sDDF)_Lucy_Parker.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-sDDF">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Multiprocessing-verified-kernels"><%@ include file="abstracts/Multiprocessing-verified-kernels.pml" %><a href="https://youtu.be/ooIPe4wRMKk" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_07_Multiprocessing_on_seL4_with_verified_kernels_Kent_Mcleod.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Multiprocessing-verified-kernels">See this talk in the program</a></div>
<div class="summit-abstract" id="a-QEMU-extend-VirtIO"><%@ include file="abstracts/QEMU-extend-VirtIO.pml" %><a href="https://www.youtube.com/watch?v=qjtY2O1ViGs" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_08_Using_QEMU_to_extend_seL4_VirtIO_support_Hannu_Lyytinen.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-QEMU-extend-VirtIO">See this talk in the program</a></div>
<div class="summit-abstract" id="a-QEMU-prototyping-platform"><%@ include file="abstracts/QEMU-prototyping-platform.pml" %><a href="https://www.youtube.com/watch?v=R-HNQK1uA7c" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_09_QEMU_as_prototyping_platform_for_seL4_systems_Axel_Heider.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-QEMU-prototyping-platform">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Porting-U-Boot"><%@ include file="abstracts/Porting-U-Boot.pml" %><a href="https://www.youtube.com/watch?v=FfdrOKder_U" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_10_Porting_U-Boot_drivers_to_seL4_Mark_Jenkinson_&_Stephen_Williams.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Porting-U-Boot">See this talk in the program</a></div>
<div class="summit-abstract" id="a-fence-t"><%@ include file="abstracts/fence-t.pml" %><a href="https://www.youtube.com/watch?v=tLcum9YksJM" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d1_11_fence.t_hardware_support_for_preventing_microarchitectural_timing_channels_Nils_Wistoff.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-fence-t">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Kry10-Secure-Platform"><%@ include file="abstracts/Kry10-Secure-Platform.pml" %><a href="https://www.youtube.com/watch?v=YG5BaoB24eA" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d2_01_Kry10_Secure_Platform_Boyd_Multerer.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Kry10-Secure-Platform">See this talk in the program</a></div>
<div class="summit-abstract" id="a-seL4-BEAM"><%@ include file="abstracts/seL4-BEAM.pml" %><a href="https://youtu.be/owmvgUwBlJ0" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d2_03_seL4_and_BEAM_a_match_made_in_Erlang_Ihor.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-seL4-BEAM">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Trustworthy-board-management"><%@ include file="abstracts/Trustworthy-board-management.pml" %><a href="https://www.youtube.com/watch?v=mCYxdn4bWw4" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d2_04_Trustworthy_board_management_controllers_Daniel_Schwyn,_Ben_Fiedler.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Trustworthy-board-management">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Rust-support"><%@ include file="abstracts/Rust-support.pml" %><a href="https://www.youtube.com/watch?v=FXB4hGZUilU" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d2_05_Rust_support_in_seL4_userspace_present_and_future_Nick Spinale.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Rust-support">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Network-stack-implementation"><%@ include file="abstracts/Network-stack-implementation.pml" %><a href="https://youtu.be/linRvpquOrg" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d2_06_Early_experiences_proving_the_correctness_of_a_network_stack_implementation_Alain_Kägi.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Network-stack-implementation">See this talk in the program</a></div>
<div class="summit-abstract" id="a-CASE-overview"><%@ include file="abstracts/CASE-overview.pml" %><a href="https://youtu.be/SY9GHV_5agM" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d2_07_CASE_overview_Cyber_Assured_Systems_Engineering_Darren_Cofer.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-CASE-overview">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Verified-architecture"><%@ include file="abstracts/Verified-architecture.pml" %><!--a href="" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a-->
    <a href="slides/d2_08_A verified architecture for trustworthy remote attestation_Grant Jurgenson.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Verified-architecture">See this talk in the program</a></div>
<div class="summit-abstract" id="a-FerrOS"><%@ include file="abstracts/FerrOS.pml" %><a href="https://www.youtube.com/watch?v=osepBlSQjY8&t=4s" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d2_09_FerrOS_Rust-y_unikernels_on_seL4_w_compile-time_assurances_Zack_Pierce.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-FerrOS">See this talk in the program</a></div>

<!--Safety-critical-voice.-->

<div class="summit-abstract" id="a-ASIL-D"><%@ include file="abstracts/ASIL-D.pml" %><a href="https://youtu.be/x69C4SVRbKo" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d2_10_Make_seL4_an_ASIL-D_certified_system_Yuning_Liang.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-ASIL-D">See this talk in the program</a></div>

<!--TCCOE-->

<div class="summit-abstract" id="a-Funding-agencies"><%@ include file="abstracts/Funding-agencies.pml" %></div>
<div class="summit-abstract" id="a-Funding-agencies-darpa"><%@ include file="abstracts/Funding-agencies-darpa.pml" %></div>
<div class="summit-abstract" id="a-Funding-agencies-ncsc"><%@ include file="abstracts/Funding-agencies-ncsc.pml" %></div>
<div class="summit-abstract" id="a-Funding-agencies-cyberagentur"><%@ include file="abstracts/Funding-agencies-cyberagentur.pml" %></div>
<div class="summit-abstract" id="a-Funding-agencies-tii"><%@ include file="abstracts/Funding-agencies-tii.pml" %></div><!--a href="https://youtu.be/ycoUg3pP40k" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a-->
<a href="program.pml#p-Funding-agencies">See this talk in the program</a>
<div class="summit-abstract" id="a-seL4-principles-abstractions"><%@ include file="abstracts/seL4-principles-abstractions.pml" %></div><a href="https://www.youtube.com/watch?v=xszOcZnR_lg" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_01_Overview_seL4_principles,_abstractions_and_use_Gernot_Heiser.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-seL4-principles-abstractions">See this talk in the program</a>
<div class="summit-abstract" id="a-Whats-verified"><%@ include file="abstracts/Whats-verified.pml" %><a href="https://www.youtube.com/watch?v=zUpq3c0_b_s" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_02_Overview_what's_verified,_what's_not,_and_what_does_it_mean_June_Andronick.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Whats-verified">See this talk in the program</a></div>
<div class="summit-abstract" id="a-GitHub-tests"><%@ include file="abstracts/GitHub-tests.pml" %><a href="https://www.youtube.com/watch?v=5LlXQUjefTc" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_03_The_seL4_GitHub_test_suite_Gerwin_Klein.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-GitHub-tests">See this talk in the program</a></div>
<div class="summit-abstract" id="a-seL4-mainlining"><%@ include file="abstracts/seL4-mainlining.pml" %><a href="https://www.youtube.com/watch?v=OBrSov78KcY" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_04_seL4_mainlining_experiences,_challenges,_and_solutions_Robbie.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-seL4-mainlining">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Standard-VMM"><%@ include file="abstracts/Standard-VMM.pml" %><a href="https://www.youtube.com/watch?v=j0mcjByf6PM" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_05_seL4_microkernel_for_virtualization_use-cases “The importance of a standard VMM”.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Standard-VMM">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Improving-embedded-DevOps"><%@ include file="abstracts/Improving-embedded-DevOps.pml" %><a href="https://www.youtube.com/watch?v=rocLV9xl2MQ" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_06_Improving_embedded_DevOps_with_seL4_VMM.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Improving-embedded-DevOps">See this talk in the program</a></div>
<div class="summit-abstract" id="a-Experience-teaching-seL4"><%@ include file="abstracts/Experience-teaching-seL4.pml" %><a href="https://youtu.be/5xl7e0J9_3A" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_07_Experience_teaching_seL4.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-Experience-teaching-seL4">See this talk in the program</a></div>
<div class="summit-abstract" id="a-VM-Composer"><%@ include file="abstracts/VM-Composer.pml" %><a href="https://www.youtube.com/watch?v=r6b1ehTQCHI&t=1s" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_08_DornerWorks’_VM_Composer.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-VM-Composer">See this talk in the program</a></div>
<div class="summit-abstract" id="a-seL4-Foundation"><%@ include file="abstracts/seL4-Foundation.pml" %><a href="https://www.youtube.com/watch?v=ABqQqgf6ez8" target="_blank"><img src="../../images/icons/youtube_nobckgnd.svg" class="youtube_icon" alt="YouTube icon"></a>&nbsp;&nbsp;<a href="slides/d3_09_seL4_Foundation_overview,_update_and_vision.pdf"><img src="../../images/icons/slides.svg" alt="slides icon"></a><br><a href="program.pml#p-seL4-Foundation">See this talk in the program</a></div>
<div class="summit-abstract" id="a-zero-hello-world"><%@ include file="abstracts/zero-hello-world.pml" %>
<a href="program.pml#p-zero-hello-world">See this talk in the program</a></div>
<div class="summit-abstract" id="a-CAmkES"><%@ include file="abstracts/CAmkES.pml" %>
<a href="program.pml#p-CAmkES">See this talk in the program</a></div>
<div class="summit-abstract" id="a-TRENTOS"><%@ include file="abstracts/TRENTOS.pml" %>
<a href="program.pml#p-TRENTOS">See this talk in the program</a></div>
<div class="summit-abstract" id="a-seL4CP-bootcamp"><%@ include file="abstracts/seL4CP-bootcamp.pml" %>
<a href="program.pml#p-seL4CP-bootcamp">See this talk in the program</a></div>
<div class="summit-abstract" id="a-VM-Composer-bootcamp"><%@ include file="abstracts/VM-Composer-bootcamp.pml" %>
<a href="program.pml#p-VM-Composer-bootcamp">See this talk in the program</a></div>
<div class="summit-abstract" id="a-BriefCASE-tutorial"><%@ include file="abstracts/BriefCASE-tutorial.pml" %>
<a href="program.pml#p-BriefCASE-tutorial">See this talk in the program</a></div>

<p>
<strong><br>Acknowledgement: </strong>
<a href="https://www.flaticon.com/free-icons/explanation" title="explanation icons">Slide icons create by Syahrul Hidayatullah - Flaticon</a>
</p>