# Copyright 2021, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Test Bamboo summary script

name: Bamboo Test

on:
  pull_request:
    paths:
      - 'bamboo/**'

jobs:
  bamboo:
    name: 'Test summary script'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: cd bamboo; make
