# Copyright 2024, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# Build and deploy the site

name: Deploy Site

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1 # sets up ruby according to .ruby-version and caches bundler deps
      with:
        bundler-cache: true
    - run: make build JEKYLL_ENV=production
    - run: tar -cvf site.tar _site/
    - uses: actions/upload-artifact@v4
      with:
        name: site
        path: site.tar

  build-seL4:
    name: Build site (seL4)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1 # sets up ruby according to .ruby-version and caches bundler deps
      with:
        bundler-cache: true
    - run: make on_seL4 JEKYLL_ENV=production
    - run: tar -cvf site.tar _site_on_seL4/
    - uses: actions/upload-artifact@v4
      with:
        name: site-seL4
        path: site.tar

  deploy_seL4:
    if: ${{ github.repository_owner == 'seL4' &&
            (github.event_name == 'push' ||
             github.event_name == 'workflow_dispatch') }}
    needs: build-seL4
    name: 'Deploy to seL4 server'
    runs-on: ubuntu-latest
    steps:
      - name: Get site
        uses: actions/download-artifact@v4
        with:
          name: site-seL4
      - name: Unpack
        run: tar -xvf site.tar
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.WEB_DEPLOY_KEY }}
      - name: Add host keys
        run: |
          echo ${{ secrets.WEB_HOST_KEYS }} > ~/.ssh/known_hosts
      - name: rsync
        run: |
          rsync -a --delete -e 'ssh -J web-updater@login.trustworthy.systems' _site_on_seL4/ web-updater@tftp.keg.cse.unsw.edu.au:/vmm-work/www

  deploy_backup:
    if: ${{ github.repository_owner == 'seL4' &&
            (github.event_name == 'push' ||
              github.event_name == 'workflow_dispatch') }}
    needs: build
    name: 'Deploy to backup server'
    runs-on: ubuntu-latest
    steps:
      - name: Get site
        uses: actions/download-artifact@v4
        with:
          name: site
      - name: Unpack
        run: tar -xvf site.tar
      - name: Set up ssh agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.WEB_DEPLOY_KEY }}
      - name: Add host keys
        run: |
          echo ${{ secrets.WEB_HOST_KEYS }} > ~/.ssh/known_hosts
      - name: rsync
        run: |
          rsync -a --delete _site/ web-updater@lists.sel4.systems:/var/www/html/seL4

  deploy_branch:
    if: ${{ github.repository_owner == 'seL4' &&
            (github.event_name == 'push' ||
             github.event_name == 'workflow_dispatch') }}
    needs: build
    name: 'Deploy gh_pages branch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        token: ${{ secrets.PRIV_REPO_TOKEN }}
    # for removing files, we need to start fresh; this does not remove dot-files
    # leaves .nojekyll in place
    - run: rm -rf *
    - uses: actions/download-artifact@v4
      with:
        name: site
    - run: tar -xvf site.tar
    - run: cp -a _site/* .
    - run: rm -rf site.tar _site
    # recreate CNAME file for GitHub; not included in generated site
    - run: echo sel4.systems > CNAME
    # add/remove everything
    - run: git add -A .
    - run: git diff --cached
    - run: git config user.name "CI"
    - run: git config user.email ci@sel4.systems
    - run: git commit -m "auto-deployed"
    - run: git push
